### ISSUE TITLE
Add CONTRIBUTORS.md

### ISSUE THREAD

**Issue by chrzyki** [lexibank/daniellinguafrancas#10]
See here for an example:

https://github.com/lexibank/bowernpny/blob/master/CONTRIBUTORS.md

In addition to `Author`, `Creator`, and `Maintainer` for the Zenodo 'Creators' category, the following roles are possible:

https://github.com/lexibank/pylexibank/blob/77efd5a465892a29f2958fe58e4b1c5d6546f5f7/src/pylexibank/metadata.py#L19-L41

**Comment by ilchec** [comment]
Pushed the file with contributors.
