### ISSUE TITLE
Value splitting

### ISSUE THREAD

**Issue by chrzyki** [lexibank/daniellinguafrancas#11]
I'm not too familiar with this dataset so apologies if this has already been talked about/if it already has been considered.

The `Form` column does seem to have a number of separators (most notably `//` and `/`). Should these have been splits?

**Comment by ilchec** [comment]
Not sure what you mean, but the entries in the data should not be segmented at all (it's not a historical-comparative dataset).

**Comment by chrzyki** [comment]
I'm referring to forms like `хоНхóл // хваНхáл`, `эргъвáн / иргъвáн`, etc. They appear in the `Form`s column and it seems to me like they should have been split into separate forms from the `Value`s column.

**Comment by LinguList** [comment]
Right, this is important @ilchec, a good catch, @chrzyki. What separators do you use for multiple words in the same cell, @ilchec ?

**Comment by ilchec** [comment]
Yep, got it. Should be // and /, I think, I'll look for more. I never looked into these cases because they are the same lexeme and in these data they don't need to be separated (it doesn't change anything content-wise). The words that are actually different (not just different spellings of the same words) have been taken care of. Since we do nothing with the form here, is it possible to just leave them this way?

**Comment by LinguList** [comment]
Then one should only include the first form. In the FormSpec, you should
add: `first_form_only=True` (please check the parameter interactively, I
don't recall it). Specifying "/" is enough, since separators have to be
single characters, but this will yield the same result.

**Comment by ilchec** [comment]
Not sure how it's supposed to work. I removed the hashes from the form_spec definition and added the first_form_only to the code as follows:

    form_spec = FormSpec(
    #    brackets={"(": ")", "[": "]"},
        separators=";/,",
        first_form_only=True,
    #    missing_data=("?", "-"),
    #    strip_inside_brackets=True,
    )

But what function should the form_spec be fed to? Right now none of the functions use it and just doing this didn't change the output.

**Comment by LinguList** [comment]
The function is an attribute of the class. It is activated upon
"add_forms_from_value"

Currently, you use "add_form", which means you dont use the formspec, so
you should replace this with:

add_forms_from_value(Language_ID, Parameter_ID, Value=form, Source=Source)

so you do not pass Form as an argument

**Comment by ilchec** [comment]
I tried doing it different ways, none of which worked. Can you please look at the code or give me a more detailed instruction please?

**Comment by LinguList** [comment]
I make an update as PR, please inspect this carefully.

**Comment by LinguList** [comment]
I have just updated the code, please check the CLDF format, @ilchec, to see if the splitting has worked properly (the field "FORM" should have taken only the first part of multiwords per cell).

**Comment by LinguList** [comment]
The code is hopefully explaining this properly enough.

**Comment by ilchec** [comment]
Yes, it worked well, thank you! And now I get what had to be done, the code is clear as day =)

**Comment by LinguList** [comment]
@chrzyki, I think this can be submitted to Zenodo now. Thanks a lot for
looking into this.

**Comment by chrzyki** [comment]
I think the notes are from another dataset?

https://github.com/lexibank/daniellinguafrancas/blob/main/NOTES.md

**Comment by chrzyki** [comment]
And sure, happy to help! :)

**Comment by LinguList** [comment]
Good catch, @chrzyki, I just modify this, and sent an email to Ilia! I alos move the stuff tha tis not "raw" to "scripts".

**Comment by LinguList** [comment]
@ilchec, please also add a README.md file to the scrits folder, where you point then to the Rmarkdown file to follow the analysis. I myself do not like Rmarkdown, as it is not convenient to run it as an R-script without an interactive session. But you should be able to export it, right? Yet this may be a personal preference. Anyway: we need now: NOTES.md (instructions sent per email) and scripts/README.md as a welcome page there. Then a final check of `cldf/forms.csv` and cldf/cognates.csv

**Comment by ilchec** [comment]
Will do!

Yes, you can export Rmarkdown, I think you can also transform it into an Rnotebook quite easily, although I didn't use one because when I tried to run it on my wife's laptop, it just didn't work although the code itself was working fine, so I thought Rmarkdown is a more reliable solution.
