### ISSUE TITLE
Many unneeded spaces in Arabic forms in words_data.tsv

### ISSUE THREAD

**Issue by LinguList** [lexibank/daniellinguafrancas#12]
Words_data.tsv has many spaces in all arabic forms. Is that intended?

**Comment by LinguList** [comment]
There are even newlines in the forms?

**Comment by ilchec** [comment]
I have no idea what this stuff is, I tried to fix it a couple times but it always keeps coming back. It doesn't affect the usability of the data though, when I open this file in a text editor, they are there, but when I read it with R or open it with my CSV editor, everything is fine. Compare text vs. R/CSV editor:

1	the ant	1 - 4	"نَمْلَة
"	149	E_Arabic	nam̊laẗ	4	NA	bulakhpc	NA	NA	NA

<img width="1159" alt="Screenshot 2021-01-21 at 09 46 38" src="https://user-images.githubusercontent.com/32166405/105326028-915ac380-5bcd-11eb-9790-1caeaf18b9a9.png">

**Comment by ilchec** [comment]
Oh, probably it's because R automatically treats the quotes as an escape character.

**Comment by ilchec** [comment]
Okay, I removed the newlines and will push the updates now.

**Comment by ilchec** [comment]
Just in case: I hope it'll stay this way in case I need to run the code again or whatever, it's not the first time that I remove those.

**Comment by ilchec** [comment]
Now it looks like the List_ID and Standard Transcription columns are reversed in the Arabic lines, but it's not true and everything work fine, it's a display artefact.
