### ISSUE TITLE
One small thing before the release ...

### ISSUE THREAD

**Issue by chrzyki** [lexibank/daniellinguafrancas#14]
Sorry, just another small question: I noticed that the title of this dataset (CLDF dataset accompanying Daniel et al.'s "Lingua Franca as Lexical Donors: Evidence from Daghestan" from 2021) deviates from our usual pattern (CLDF dataset derived from Author et al ...). Was this intentional or should this be changed @LinguList and @ilchec?

**Comment by ilchec** [comment]
I can't say much about this, as far as I remember, I simply took this sentence from a different lexibank dataset and changed the title of the paper and the authors. @LinguList?

**Comment by LinguList** [comment]
Yes, intentional, since this is a supplemented CLDF dataset that is 
published along with a paper, not a retro-standardized dataset. So I'd 
say: the "CLDF Datsets Accompanying" should be our title for the future 
for datasts published ALONG with a study.

**Comment by chrzyki** [comment]
Thanks for clarifying!
