### ISSUE TITLE
need admin rights to transfer repository

### ISSUE THREAD

**Issue by LinguList** [lexibank/daniellinguafrancas#3]
by now, I do not have those. Alternatively, I make a repo for lexibank and you add the data, @ilchec ?

**Comment by ilchec** [comment]
But I just transferred the ownership in this "dangerous" zone, it says the repo is pending the transfer acceptance from you. Okay, I'll abort the transfer and do it myself then!

**Comment by LinguList** [comment]
Ah, I saw I have to accept this. And since you have this repo on your own account, this means you cannot just transfer it, as it will then be on my account, etc.
