### ISSUE TITLE
Pre-CLDF structure?

### ISSUE THREAD

**Issue by ilchec** [lexibank/daniellinguafrancas#4]
@LinguList Hi Mattis! I pushed the new languages.tsv, new sources.tsv and added sources to words_data.tsv. How can I create the files and the folders that you added to the chechuroborrowings repo? I'd like to learn to do it myself.

**Comment by LinguList** [comment]
you need to make a script called lexibank_daniellinguafrancas.py and 
modify this accordingly. You also need to change the "setup.py" by 
replacing the names there. That is basically all. You can copy-paste the 
scripts first and then adjust. Then python-install them (as you did 
before) and all should hopefully work ;)

**Comment by ilchec** [comment]
Thanks! I'll try it!
