### ISSUE TITLE
Open PR

### ISSUE THREAD

**Issue by chrzyki** [lexibank/daniellinguafrancas#8]
It seems like most of the things in #5 have been put into the main repository. Can the PR be closed or is there anything in there that needs to be merged?

**Comment by ilchec** [comment]
I had troubles with this branch and it should just be removed. I made a different one and CLDFied the data there and already merged it with master, #5 should be cancelled.

**Comment by ilchec** [comment]
I'll also remove the branch, to avoid confusion.

**Comment by chrzyki** [comment]
Thanks!
