### ISSUE TITLE
raw/ has a lot of unused artifacts

### ISSUE THREAD

**Issue by chrzyki** [lexibank/daniellinguafrancas#9]
`cmd_makecldf()` only uses `words_data.tsv` in `raw/`. Are the other artifacts needed? (I'm specifically thinking that they would be versioned with Zenodo. If those are not needed it might be worth it to remove them OR explain their use in a `NOTES.md`.)

**Comment by ilchec** [comment]
Yes, that's the code and other stuff, they are not used directly here but are relevant for the paper. I'd like to keep them if possible (removing is also an option, I'll upload it to the journal's repo anyway, but having them here would be good). I'll add the explanations to the NOTES.md.

**Comment by LinguList** [comment]
I'd propose to add those to a folder "script", and add a "README.md", where you explain how to replicate the code. Then you add a note to NOTES.md, specifying that the code for the paper can be found in there?
